//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MyPlayer.rc
// 
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDC_MENU_NEW                    101
#define IDD_MYPLAYER_DIALOG             102
#define IDL_LIST_OPEN1                  102
#define IDL_LIST_OPEN2                  103
#define IDL_LIST_OPEN3                  104
#define IDL_LIST_OPEN4                  105
#define IDL_LIST_OPEN5                  106
#define IDL_LIST_OPEN6                  107
#define IDL_LIST_OPEN7                  108
#define IDL_LIST_OPEN8                  109
#define IDL_LIST_OPEN9                  110
#define IDL_LIST_OPEN10                 111
#define IDR_MAINFRAME                   128
#define IDB_OPEN_NORMAL                 129
#define IDB_OPEN_OVER                   130
#define IDB_MAIN                        132
#define IDB_EXIT_NORMAL                 133
#define IDB_EXIT_OVER                   134
#define IDB_HIDE_NORMAL                 135
#define IDB_HIDE_OVER                   136
#define IDB_MIN_NORMAL                  137
#define IDB_MIN_OVER                    138
#define IDB_NEXT_NORMAL                 139
#define IDB_NEXT_OVER                   140
#define IDB_PLAYLIST_SHOW_NORMAL        142
#define IDB_PLAYLIST_SHOW_OVER          143
#define IDB_PLAY_NORMAL                 144
#define IDB_PLAY_OVER                   145
#define IDB_PREV_NORMAL                 146
#define IDB_PREV_OVER                   147
#define IDB_SLIDE                       148
#define IDB_SLIDEBKGND                  149
#define IDB_STOP_NORMAL                 150
#define IDB_STOP_OVER                   151
#define IDB_VOLUME                      152
#define IDD_PLAYLIST_DIALOG             153
#define IDB_PLAYLIST_HIDE_NORMAL        154
#define IDB_PLAYLIST_HIDE_OVER          155
#define IDB_PLAYLIST_MAIN               156
#define IDB_PLCLOSE_NORMAL              157
#define IDB_PLCLOSE_OVER                158
#define IDD_LYRIC_DIALOG                159
#define IDB_ADD_NORMAL                  161
#define IDB_ADD_OVER                    162
#define IDB_DEL_NORMAL                  163
#define IDB_DEL_OVER                    164
#define IDB_LIST_NORMAL                 165
#define IDB_LIST_OVER                   166
#define IDB_LYRIC_HIDE_NORMAL           167
#define IDB_LYRIC_HIDE_OVER             168
#define IDB_LYRIC_SHOW_NORMAL           169
#define IDB_LYRIC_SHOW_OVER             170
#define IDR_MENU_ADD                    171
#define IDR_MENU_DEL                    172
#define IDR_MENU_LIST                   173
#define IDD_NEWLIST_DIALOG              174
#define IDD_RENAME_DIALOG               175
#define IDD_DEL_LIST_DIALOG             176
#define IDD_MENE_DIALOG                 178
#define IDR_MENU_MAIN                   179
#define IDB_MENUSHOW                    180
#define IDB_MENU                        181
#define IDR_MENU_RBCLICK_LIST           183
#define IDD_FILEATTRIBUTE_DIALOG        184
#define IDR_MENU_HIDEMAIN               185
#define IDC_BTN_OPEN                    1000
#define IDC_BTN_PLAY                    1001
#define IDC_BTN_STOP                    1002
#define IDC_BTN_PREV                    1003
#define IDC_BTN_NEXT                    1004
#define IDC_BTN_HIDE                    1005
#define IDC_BTN_MIN                     1006
#define IDC_BTN_EXIT                    1007
#define IDC_BTN_PLAYLIST_SHOW           1008
#define IDC_STATIC_PLAY                 1011
#define IDC_STATIC_MODE                 1012
#define IDC_BTN_SLIDE                   1013
#define IDC_BTN_VOLUME                  1014
#define IDC_BTN_CLOSE                   1015
#define IDC_PLAYLIST                    1016
#define IDC_BTN_ADD                     1017
#define IDC_BTN_DEL                     1018
#define IDC_BTN_LIST                    1019
#define IDC_BTN_LYRIC                   1020
#define IDC_EDIT_NAME                   1021
#define IDC_COMBO_LIST                  1023
#define IDC_BTN_SHOWMENU                1025
#define IDC_STARWARS                    1026
#define IDC_EDIT_PATH                   1027
#define IDC_STATIC_SIZE                 1029
#define IDC_ADD_FILE                    32771
#define IDC_ADD_FOLDER                  32772
#define IDC_DEL_SELECT                  32773
#define IDC_DEL_ALL                     32774
#define IDC_LIST_OPEN                   32775
#define IDC_LIST_NEW                    32776
#define IDC_LIST_DEL                    32777
#define IDC_LIST_SAVE                   32778
#define IDC_LIST_RENAME                 32779
#define IDC_ABOUT_STAR                  32780
#define IDC_MENU_PLAY                   32781
#define IDC_MENU_PAUSE                  32782
#define IDC_MENU_STOP                   32783
#define IDC_MENU_PREV                   32784
#define IDC_MENU_NEXT                   32785
#define IDC_MENU_OPEN                   32786
#define IDC_MENU_VOLUP                  32787
#define IDC_MENU_VOLDOWN                32788
#define IDC_MENU_VOLSLC                 32789
#define IDC_MENU_RAND                   32790
#define IDC_MENU_SEQ                    32791
#define IDC_MENU_SINGLE                 32792
#define IDC_SET_LYRICPATH               32795
#define IDC_MENU_OPEN_LYRICPATH         32796
#define IDC_SEND_FOLDER                 32797
#define IDC_SEND_DISK                   32798
#define IDC_FILE_ATTRIBUTE              32799
#define IDC_HIDE_MAIN                   32800
#define IDC_HIDE_LYRIC                  32801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
